name: bakery_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  #flutterfire_ui: ^0.4.3+20
  # device_preview: ^1.1.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  bottom_sheet_bar: ^2.3.9
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  cloud_firestore: ^4.8.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  dio: ^5.2.1+1
  #dio_logger: ^4.0.8+8
  url_launcher: ^6.1.11
  #firebase_core_platform_interface: ^4.5.1
  csv: ^5.0.2
  flutter_sheet_localization: ^5.1.1
  intl: ^0.17.0
  pin_input_text_field: ^4.5.0
  otp_autofill: ^2.1.0
  cached_network_image: ^3.2.3
  razorpay_flutter: ^1.3.4
  image_picker: ^0.8.6





dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^1.10.0
  flutter_sheet_localization_generator:



flutter:
  uses-material-design: true
  assets:
   - assets/placeholders/
   - assets/dashboard/icons/
   - assets/common/icons/
   - assets/home/icons/
   - assets/home/
   - assets/walkthrough/
   - assets/common/

  fonts:
   - family: WorkSans
     fonts:
       - asset: fonts/work_sans/WorkSans-Regular.ttf
       - asset: fonts/work_sans/WorkSans-SemiBold.ttf
       - asset: fonts/work_sans/WorkSans-Medium.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
